### ISSUE TITLE
using goroutines

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#11]
Does the server invoke each handler in a new goroutine? 

I was reading a bit about the http package and I think I see similarities with how you made your library. From what I read, a webserver seems to invoke each handler in a new goroutine.

edit: connections are probably different in osc...
https://eli.thegreenplace.net/2019/on-concurrency-in-go-http-servers/

**Comment by avlapp** [comment]
From the server example, as far as I understand, the fact that it returns a error, makes it hard to start it in a new goroutine, do I understand that correct?

err := serv.ListenAndServe("127.0.0.1:1234", mux)
	if err != nil {
		log.Println(err)
	}

It looks like the osc package from sclang tries to make it possible to handle stuff in goroutines: https://github.com/scgolang/osc

How well is gosc suited to be used with goroutines?

**Comment by loffa** [comment]
The server could start an goroutine as well. But like the http package it is up to the user to specify it in their code. `serv.ListenAndServe` will return an error only if the listener could not be started. Such as if the port is already in use. 

I see little benefit right now to handle each incoming data-package in a separate goroutine. Since the complexity is increased a lot for the lib by doing so. The OSC handling should be fast anyway since the protocol is made for sound mixers and mostly fast paced request/responses.
