### ISSUE TITLE
LGPL vs a permissive license

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#2]
You've chosen for a LGPL license. Might be a reasonable choice. A disadvantage might be that someone can fork it to GPL3 and then you can't use that code in your own LGPL software. 

A MIT license, might provide you with even more contributions then LGPL cause more developers might be going to use it. They would in general have little reasons to keep it for themselves, as it gives them much more workload.

This might be a interesting read (keyword 'viral'):
https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/2020-12/EUPL%20overview%202020_0.pdf

This is a good read as well about GPL vs MIT, but it seems to be offline
The labyrinth of software freedom by Nikolai Bezroukov,

**Comment by loffa** [comment]
Thank you for the comment.

LGPL V3 is more commonly used for libraries since it allows derived programs that only uses the public interface of the library to be closed source. This allows someone to use the library as-is in their closed source product but forks of the original lib will be either LGPL or GPL.

The description mentions this:
> However, a larger work using the licensed work through interfaces provided by the licensed work may be distributed under different terms and without source code for the larger work.

**Comment by avlapp** [comment]
My point was that someone can fork your library to GPL 3 (not LGPL) and you're stuck. Then you can't use code from the forked project (GPL) in your original project (LGPL).

LGPL allows forking to GPL. And while GPL is not LGPL, one can only use that code in GPL projects (not LGPL).

**Comment by loffa** [comment]
If that happens and the fork starts adding features to the repo there is nothing stopping me from using that instead. Since it still will be forced to obey to the openness of the GPL3 licence.

If this repo where to switch to GPL, I would loose the ability to use it in close-source software which I need for work related development.

**Comment by avlapp** [comment]
> If that happens and the fork starts adding features to the repo there is nothing stopping me from using that instead. Since it still will be forced to obey to the openness of the GPL3 licence.

This is about a situation where someone forks your project and chooses a GPL license for it, instead of LGPL. This is allowed. 

But then you can't use GPL code in LGPL software. So there is actually something stopping you from using the added features, the GPL license. It means, that you need to switch to GPL to, if you want to use that code. 

You can use LGPL sofware in GPL software, but not vice versa. 

> 
> If this repo where to switch to GPL, I would loose the ability to use it in close-source software which I need for work related development.

Sure, I don't suggest GPL, LGPL makes more sense for a library as this, but a MIT license maybe even more so.

**Comment by avlap** [comment]
The problem I describe is similar to what  Thorvalds describes here:
https://youtu.be/PaKIZ7gJlRU?t=206

LGPL is compatible with GPL, but GPL not with LGPL.
