### ISSUE TITLE
[question] make a Message

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#9]
Being new to golang, this breaks my brain:

type Message struct {
	// The Address is a '/' separated string as per the specification
	Address [string](https://pkg.go.dev/builtin#string)
	// Arguments is the array of that that is written when the package is sent.
	// Only data-types with defined writers is supported.
	Arguments [][any](https://pkg.go.dev/builtin#any)
}

Could you give an example of such Arguments?

Do I miss something? It looks so simple in pyliblo:

http://dsacre.github.io/pyliblo/doc/#liblo.Message

This function needs a Message:

func (c *[Client](https://pkg.go.dev/github.com/loffa/gosc#Client)) SendAndReceive[Message](https://pkg.go.dev/github.com/loffa/gosc#Message)(msg *[Message](https://pkg.go.dev/github.com/loffa/gosc#Message)) (*Message, [error](https://pkg.go.dev/builtin#error))

**Comment by loffa** [comment]
``Since Golang is a much stricter typed language then python the type of the payload needs to be writable by the writer. Looking at defined writers [here](https://github.com/loffa/gosc/blob/master/type_tags.go#L46) we can see what types is avalible and completed at the moment. The corresponding Golang type is used for the type-tag of the OSC message.

I also added a convenience method on the client for creating messages on the fly called `EmitMessage` [here](https://github.com/loffa/gosc/blob/master/client.go#L103) that will create the message and send it without waiting for a response.

As you requested an example:
```golang
msg := &Message{
	Address: "/hello",
	Arguments: []any{
		float32(23.4),
		"hello",
	},
}
```
